import React from 'react';
import { Box, Container, Typography, Grid } from '@mui/material';
import AboutPageVector from '../assets/AboutPageVector.png';

const aboutSections = [
  {
    title: 'The Modern Expense Management Landscape',
    content: `The expense management market is a mature and highly competitive space, characterized by sophisticated incumbents and disruptive new entrants. To successfully launch a new AI-powered expense tracker, a deep understanding of the strategic landscape is not merely advantageous; it is a prerequisite for survival. This involves a granular analysis of market segments, a deconstruction of competitor business models, and a clear-eyed assessment of the pricing and integration strategies that define success in this domain.`
  },
  {
    title: 'Market Segmentation & Opportunity Analysis',
    content: `The market for expense management solutions is clearly stratified into three primary user groups: Individuals/Freelancers, Small to Medium-sized Businesses (SMBs), and Large Enterprises. Each segment possesses distinct needs, pain points, and willingness to pay, which dictates the required feature set and go-to-market strategy.`
  },
  {
    title: 'Competitive Deep Dive: Expense vs. Spend Management',
    content: `The competitive field can be divided into two strategic categories: pure expense management platforms and all-in-one spend management platforms. Pure Expense Management: Platforms like Expensify, SparkReceipt, and Zoho Expense focus on perfecting the workflow of capturing, reporting, and reimbursing expenses after they have occurred. All-in-One Spend Management: A newer and highly disruptive category is led by companies like Ramp and BILL (formerly Divvy). These platforms go beyond post-transaction reporting by integrating corporate cards, bill payments, and expense management into a unified financial operating system.`
  },
  {
    title: 'Winning Strategies: Pricing, Integrations, and Go-to-Market',
    content: `The business model is arguably the most critical strategic decision. The market features a variety of pricing strategies, from freemium and per-user SaaS fees to interchange-driven models. Pure expense management tools typically employ a SaaS model. Spend management platforms like Ramp and BILL have disrupted this model by offering their sophisticated software for free, monetizing through interchange fees generated by their integrated corporate card. The integration ecosystem serves as a critical competitive moat. Seamless, bi-directional synchronization with accounting software is a non-negotiable requirement for any business-focused tool.`
  }
];

export default function About() {
  return (
    <Box sx={{ bgcolor: 'background.default', minHeight: '100vh', py: { xs: 6, md: 10 } }}>
      <Container maxWidth="lg">
        <Grid container spacing={4} alignItems="flex-start" justifyContent="flex-start">
          <Grid item xs={12} md={8}>
            <Box sx={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', mb: 4, flexDirection: { xs: 'column', md: 'row' } }}>
              <Box sx={{ flex: 1, pr: { md: 4 }, mb: { xs: 3, md: 0 } }}>
                <Typography variant="h1" sx={{ fontWeight: 700, fontFamily: 'Cormorant Garamond, serif', color: 'primary.main', mb: 2, fontSize: { xs: '2rem', md: '2.5rem' } }}>
                  About BUDGRO
                </Typography>
                <Typography variant="body1" sx={{ color: 'text.secondary', mb: 2, fontSize: { xs: '1.1rem', md: '1.15rem' } }}>
                  Building a Competitive AI-Powered Expense Tracking Platform: A Strategic and Technical Blueprint for the MERN Stack
                </Typography>
              </Box>
              <Box sx={{ flexShrink: 0, width: { xs: '100%', md: 260 }, ml: { md: 2 }, display: 'flex', justifyContent: 'flex-end' }}>
                <img src={AboutPageVector} alt="About BUDGRO" style={{ width: '100%', maxWidth: 260, height: 'auto', borderRadius: 0, boxShadow: 'none', display: 'block' }} />
              </Box>
            </Box>
            {aboutSections.map((section) => (
              <Box key={section.title} sx={{ mb: 4 }}>
                <Typography variant="h2" sx={{ fontWeight: 600, fontFamily: 'Cormorant Garamond, serif', color: 'primary.main', mb: 1, fontSize: { xs: '1.2rem', md: '1.5rem' } }}>
                  {section.title}
                </Typography>
                <Typography variant="body1" sx={{ color: 'text.primary', fontFamily: 'Inter, Arial, sans-serif', fontWeight: 400, fontSize: { xs: '1rem', md: '1.08rem' } }}>
                  {section.content}
                </Typography>
              </Box>
            ))}
          </Grid>
        </Grid>
      </Container>
    </Box>
  );
}
